// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvuiiexzdntr8AkSRmsJ9c7h03DkckFc',
    appId: '1:117984014547:web:2f7d7dc7f0159a96fd2426',
    messagingSenderId: '117984014547',
    projectId: 'libro-y-punto',
    authDomain: 'libro-y-punto.firebaseapp.com',
    storageBucket: 'libro-y-punto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaMh3vmk72XPC6jn_c8I0gCu4azj7fJM',
    appId: '1:117984014547:android:ec94d6a7a15a6ed8fd2426',
    messagingSenderId: '117984014547',
    projectId: 'libro-y-punto',
    storageBucket: 'libro-y-punto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHKEmj_KTG-yhx2SZj1Vot4nsSzLa6Fw',
    appId: '1:117984014547:ios:47bc14f1b5920907fd2426',
    messagingSenderId: '117984014547',
    projectId: 'libro-y-punto',
    storageBucket: 'libro-y-punto.firebasestorage.app',
    iosBundleId: 'com.example.lypflutter2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwvuiiexzdntr8AkSRmsJ9c7h03DkckFc',
    appId: '1:117984014547:web:9350a852ccc87a01fd2426',
    messagingSenderId: '117984014547',
    projectId: 'libro-y-punto',
    authDomain: 'libro-y-punto.firebaseapp.com',
    storageBucket: 'libro-y-punto.firebasestorage.app',
  );

}